apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
        - name: frontend
          image: movie-frontend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
